### ISSUE TITLE
Windows: Start testing classes with multithreading enabled fails

### ISSUE THREAD

**Issue by infeo** [cryptomator/jfuse#31]
Omitting the FUSE single thread option (`-s`), activates mulithreading.

But on Windows all adequate test classes fail to start with:
```
org.cryptomator.jfuse.api.FuseMountFailedException: Exception when starting fuse_loop. Message: unresolved symbol: fuse3_loop_mt
	at org.cryptomator.jfuse.api@0.6.0-SNAPSHOT/org.cryptomator.jfuse.api.Fuse.mount(Fuse.java:138)
	at org.cryptomator.jfuse.win@0.6.0-SNAPSHOT/org.cryptomator.jfuse.win.FuseImpl.mount(FuseImpl.java:37)
	at org.cryptomator.jfuse.examples@0.6.0-SNAPSHOT/org.cryptomator.jfuse.examples.WindowsMirrorFileSystem.main(WindowsMirrorFileSystem.java:34)
```

I believe this is related to the fact, that in the winfsp DLL, `fuse3_loop_mt` and `fuse3_loop_mt_31` map to the same virtual address, as it can be see with the [Dependencies](https://github.com/lucasg/Dependencies) app:
![grafik](https://user-images.githubusercontent.com/9036915/230108387-36f47f9a-c4a0-49fa-99ab-3c63b0741284.png)

**Comment by infeo** [comment]
Info: Using `fsp_fuse3_loop_mt_31` does the trick. I guess, because the symbol is defined after the normal loop function, it overwrites some internal definition.
