### ISSUE TITLE
Office 2003 (doc, xls) file save failed!

### ISSUE THREAD

**Issue by laobiao139** [cryptomator/jfuse#70]
Hello,
 I have tested the example you provided and found that WindowsMirrorFileSystem encounters errors when saving office excel 2003 files (xls) and office word 2003 files (doc). This issue is reproducible every time. Can this problem be fixed? Additionally, office versions 2007 and above can be saved normally. The tool used for editing documents is WPS.

Thank you very much.

this exception log :
```
java.nio.file.FileAlreadyExistsException: C:\Users\xxxx\Desktop\fsdownload\test\testExcel~DE996.tmp
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:119)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:309)
	at example.WindowsMirrorFileSystem.openFileChannel(WindowsMirrorFileSystem.java:67)
	at example.AbstractMirrorFileSystem.createOrOpen(AbstractMirrorFileSystem.java:457)
	at example.AbstractMirrorFileSystem.create(AbstractMirrorFileSystem.java:442)
	at org.cryptomator.jfuse.api.FuseOperationsDecorator.create(FuseOperationsDecorator.java:182)
	at org.cryptomator.jfuse.win.FuseImpl.create(FuseImpl.java:135)
```

**Comment by infeo** [comment]
The `WindowsMirrorFileSystem` is a sample filesystem, not meant for production. For a working filesystem implementation, see https://github.com/cryptomator/fuse-nio-adapter.

Of course we welcome PRs to improve the filesystem or fix bugs.
